import Layout from "@/components/Layout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/registerModal";
import { SessionProvider, getSession } from "next-auth/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
	}) {
	return (
		<html lang="en">

			<body className={inter.className}>
			<SessionProvider >
				<RegisterModal/>
				<LoginModal/>
				<Layout />
				{children}
			</SessionProvider>
			</body>
		</html>
	);
}
