

import Layout from "@/components/Layout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Modal from "@/components/Modal";
import LoginModal from "@/components/modals/LoginModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
			<html lang="en">
			<body className={inter.className}>
				<LoginModal/>
				<Layout/>
				{children}</body>
			</html>

	);
}
