import Layout from "@/components/Layout";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import ToastProvider from "@/providers/toast-provider";
import ModalProvider from "@/providers/modal-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Social media App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ToastProvider />
				<ModalProvider/>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
